### PR TITLE
Default to helm 3.3.0, also provide old helm2

### PR DESCRIPTION
**Pull request by norrs**
Leaving this here, we are upgrading .. 

Will let you know how it goes. 

I will come with some more additional patches later with support for helm2 and helm3 in here.

### CODE REVIEW

**Comment by norrs** [comment]
Confused by it saying `/home/runner/work/kubecd/kubecd/pkg/helm/values_test.go:214 +0xc6` fails, there is no line such as 214 .. 

and tests runs locally. Do you mind taking a look @stigsb  ? The concept worked when testing locally ..

**Comment by stigsb** [comment]
Now that Helm 2 is being deprecated I think it's time to go all-in with Helm 3. What do you think @norrs ?

**Comment by norrs** [comment]
@stigsb  Would still be nice to be able to specify your own binary, to help with transitions. But defaulting to "helm" in path is fine, the user can switch binaries as a workaround. 

I were supposed to make an upstream bug to either helm3 or kubernetes API (most likely compability bug), because the 3-way-diffing is tricky to solve issues with if you don't know the ninjatricks for fixing `clusterIp: ""` by editing helm configmaps/secrets and other weirdness. 

Sadly haven't been working with kubernetes for a few months.

**Comment by stigsb** [comment]
Okay, I have bumped the default Helm version in master to 3.4, would you like me to try rebasing this PR for you if you don't have time?

**Comment by norrs** [comment]
No need @stigsb

**Pull request closed without merging**
